// Each entry: the word to guess + the lyric it came from + optional song title.
// The word can be any length — the board adjusts automatically.
const WORDS = [
  { word: "SIGARET", lyric: "En een sigaret in bed en terug", song: "Wittewijnmuziek" },
  { word: "STRAK", lyric: "Tante Lien is strak", song: "Tante Lien" },
  { word: "PLATEN", lyric: "nog meer platen jawel fans", song: "Echte Echte Hiphop" },
  { word: "DANSEN", lyric: "en doe de dans die wij smurfen doen", song: "The Big Smurfout" },
  { word: "LUCIFER", lyric: "Light it up als een lucifer start", song: "Wittewijnmuziek" },
  { word: "FAFFIE", lyric: "Bestel nu je kaartjes op 1800-FAFFIE", song: "De Musical" },
  { word: "CLOCHARD", lyric: "hij komt nu van clochard", song: "Hollereer" },
  { word: "KENKER", lyric: "ke-kenker-kenk-tfu-tfu", song: "Centje Centje" },
  { word: "SICKIE", lyric: "hou het sickie zo simpel", song: "Hollereer" },
  { word: "LUISTER", lyric: "Ja nou luister, zit ik tv te kijken", song: "Hoed Rits" },
  { word: "SPLEET", lyric: "Uit de spleet van de duivel", song: "Buma In Me Zak" },
  { word: "STERREN", lyric: "1, 2, 3, 4, 5 sterren abbo", song: "Vijf Sterren Abbo" },
  { word: "STYLO", lyric: "laat die stylo verder kicken", song: "Pijpjes" },
  { word: "GARGAMEL", lyric: "Smurfgargamel, doe my own", song: "The Big Smurfout" },
  { word: "STEMPEL", lyric: "Der in, geen stempel", song: "Vijf Sterren Abbo" },
  { word: "DROMEN", lyric: "Al je dromen je weet dat ik ze", song: "Voor Jou" },
  { word: "CONDENS", lyric: "Condens op je bovenlip, tandafdrukken in je nek" },
  { word: "CHAPPEN", lyric: "yes we gaan chappen", song: "Hengel At A Bitch" },
  { word: "HITJE", lyric: "ik heb een hitje voor je", song: "Er Is Een Hitje" },
  { word: "RESPECT", lyric: "Strooi op z'n naam een paar terrabytejes respect", song: "Gemist" },
  { word: "GROEPEN", lyric: "vaak komen ze in groepen", song: "Hollereer" },
  { word: "NUCHTER", lyric: "alsof je nuchter bent", song: "Willie Wartaal Is Een Baas" },
  { word: "KERSTMAN", lyric: "Dus drink die fles leeg, ook voor de kerstman" },
  { word: "GEDRAG", lyric: "Ik heb spijt van me gedrag", song: "Sorry" },
  { word: "TASSEN", lyric: "Geef die tassen hier, dan kun je", song: "Wittewijnmuziek" },
  { word: "MOPPIE", lyric: "Als ik met mn moppie chill", song: "Shenkie" },
  { word: "NEVEL", lyric: "Door de nevel aan het lopen", song: "Een Barkie" },
  { word: "VIEZER", lyric: "Viezer dan bejaardenseks", song: "Happen Naar De Baas" },
  { word: "LOESOE", lyric: "Ik ben loesoe, en niet zo een beetjes", song: "Willie Wartaal Is Een Baas" },
  { word: "KOFFER", lyric: "Eén grote koffer en wat handbagage", song: "Wittewijnmuziek" },
  { word: "EERLIJK", lyric: "Ik zeg je eerlijk, 1, 2, 3, 4, 5", song: "Vijf Sterren Abbo" },
  { word: "PANJA", lyric: "want ik ben panja, komt door die liqua", song: "Willie Wartaal Is Een Baas" },
  { word: "SMEEK", lyric: "Smeek om vergiffenis", song: "Sorry" },
  { word: "DRANKJE", lyric: "Drink je drankje, doe je ding", song: "Willie Wartaal Is Een Baas" },
  { word: "BOETES", lyric: "boetes voor onfatsoenlijkheid", song: "Bertje Vs Yayo" },
  { word: "RODDELS", lyric: "maak de roddels maar", song: "Hollereer" },
  { word: "GEELTJE", lyric: "beetje af als een geeltje", song: "Laat De Beer Los" },
  { word: "BORNDAY", lyric: "outfit als op je bornday", song: "Luek" },
  { word: "SPACEN", lyric: "Ik hou je in de gaten ook al sta ik te spacen", song: "Drie Keer Niks" },
  { word: "EINDE", lyric: "Begin van het einde maar het einde is zoet", song: "'t Gaat Te Fur" },
  { word: "FISSIE", lyric: "Hand in mijn fissie als was ik een toz", song: "Het Mysterie Van De Koude Schouder" },
  { word: "PIEMELTJE", lyric: "stroomstoot uit het piemeltje", song: "Elektrotechnique" },
  { word: "TRUUKJES", lyric: "geen dansjes truukjes yo we spelen niks", song: "Laat De Beer Los" },
  { word: "GESNOVEN", lyric: "ik heb beetje veel coke gesnoven", song: "Centje Centje" },
  { word: "ENGEL", lyric: "Engel op me schouder", song: "Sorry" },
  { word: "GIFTIG", lyric: "giftige rhymes pas op voor oorinfecties", song: "Bekkie" },
  { word: "DERTIG", lyric: "Dertig graden zon, zit in het zand", song: "Zilt" },
  { word: "PUPILLEN", lyric: "bloeddoorlopen pupillen", song: "Bertje Vs Yayo" },
  { word: "KROKET", lyric: "heb je mijn kroket gezien neeee", song: "Laat De Beer Los" },
  { word: "KETSEN", lyric: "ik wil ketsen over een flatisc fles", song: "Pijpjes" },
  { word: "VROEGER", lyric: "Vroeger was ik best raar", song: "Stay Black" },
  { word: "BEFFEN", lyric: "begin te beffen", song: "Hengel At A Bitch" },
  { word: "WIJFJE", lyric: "van je wijfje en zo", song: "Sorry" },
  { word: "TRIPPEN", lyric: "laat me lekker trippen", song: "Flap Flap" },
  { word: "PORIE", lyric: "blood laat fur nog net porie", song: "Bekkie" },
  { word: "STANG", lyric: "Ik ben stang man, t'is geen bingo", song: "Get Spanish" },
  { word: "BABYGIRL", lyric: "Babygirl kom terug, naar m'n bedje" },
  { word: "LIPPEN", lyric: "Je lippen, je mond, je heupen", song: "Voor Jou" },
  { word: "SCHULD", lyric: "het is niet hun schuld", song: "Hollereer" },
  { word: "PUILEN", lyric: "Kijk je ogen puilen, puilen", song: "Ze Is Pas Net Begonnen" },
  { word: "KUSJES", lyric: "kusje op je wang en sorry", song: "Hengel At A Bitch" },
  { word: "GITAAR", lyric: "Effe mijn gitaar stemmen", song: "Ik Wil Me Lekkevoele" },
  { word: "VRIJDAG", lyric: "ik hou van vrijdag want we eten vis", song: "Hengel At A Bitch" },
  { word: "MORGEN", lyric: "goede morgen ben je beetje", song: "Er Is Een Hitje" },
  { word: "BILLEN", lyric: "billen en pillen klapper", song: "Flap Flap" },
  { word: "ZAPPEN", lyric: "te triestig om te zappen", song: "Bertje Vs Yayo" },
  { word: "JENEVER", lyric: "en de fles met jenever effe", song: "Centje Centje" },
  { word: "BRAND", lyric: "Zin om de hele boel in brand te steken", song: "Gemist" },
  { word: "GYMPEN", lyric: "terwijl je staat op mn gympen", song: "Hollereer" },
  { word: "PLANKJE", lyric: "brood op 't plankje", song: "Sterrenstof" },
  { word: "ZORGEN", lyric: "maak je geen zorgen ik doe dit vaker", song: "Hengel At A Bitch" },
  { word: "RAKKER", lyric: "ik ben wakker de bruine rakker", song: "Laat De Beer Los" },
  { word: "HUTSPOT", lyric: "drumstok knutselhok hutspot echt niet", song: "Bekkie" },
  { word: "MEISJE", lyric: "Blaas meisje blaas meisje maak lawaai", song: "Drie Keer Niks" },
  { word: "FEESTEN", lyric: "we gaan feesten", song: "Bertje Vs Yayo" },
  { word: "STRONT", lyric: "Door de stront" },
  { word: "BUMA", lyric: "Is er buma in me zak" },
  { word: "WANDEL", lyric: "Ik wandel, clip en draai als gasten", song: "So Duits" },
  { word: "SLAAG", lyric: "ik heb pak slaag voor die", song: "So Duits" },
  { word: "BRAKJE", lyric: "ben je beetje brakje", song: "Er Is Een Hitje" },
  { word: "HANDJES", lyric: "smurf je handjes op", song: "The Big Smurfout" },
  { word: "BRILLEN", lyric: "Zonnebrillen op en alles", song: "Bertje Vs Yayo" },
  { word: "SNEEUW", lyric: "Laat het witte vlokken sneeuwen", song: "Vette Kerst" },
  { word: "BLAUW", lyric: "blauw is de huid, wit is de outfit", song: "The Big Smurfout" },
  { word: "MOKUM", lyric: "I don't care in het mokum schijt", song: "So Duits" },
  { word: "MEESTER", lyric: "Dronken P is je heer meester", song: "Happen Naar De Baas" },
  { word: "SPEKNEK", lyric: "sjembek speknek crackhead bekkie tech", song: "Bekkie" },
  { word: "PIMPEN", lyric: "gemaakt om te pimpen", song: "Hollereer" },
  { word: "OKSEL", lyric: "Oksel ruikt naar natte hond en shit", song: "'t Gaat Te Fur" },
  { word: "DINGEN", lyric: "Praatte tegen levenloze dingen aan", song: "Stay Black" },
  { word: "DANKJE", lyric: "ik zeg dankje", song: "Sterrenstof" },
  { word: "OORBEL", lyric: "Zie ik hem met een oorbel in op een orgel", song: "Hoed Rits" },
  { word: "VERGEEF", lyric: "Vergeef me", song: "Sorry" },
  { word: "MALLE", lyric: "knallen als een malle", song: "Pijpjes" },
  { word: "VETZAK", lyric: "Rap vetzak en ik slap vet hard", song: "Drie Keer Niks" },
  { word: "SERIEUS", lyric: "ben jij nou serieus", song: "Opkepleurt" },
  { word: "WODKA", lyric: "ik sta aan de toog met een wodka", song: "Huilend Naar De Club" },
  { word: "MOOIER", lyric: "Maar ik heb een mooiere, zak mijn broek", song: "Drie Keer Niks" },
  { word: "KREKELS", lyric: "Vrat wormen en krekels", song: "Stay Black" },
  { word: "SNUIT", lyric: "Schijt is aan hou je snuit", song: "Drie Keer Niks" },
  { word: "BLAUWE", lyric: "psst, psst, blauwe broek waar", song: "Centje Centje" },
  { word: "NEURON", lyric: "een neuronenbom", song: "Elektrotechnique" },
  { word: "FRONTEN", lyric: "Dus stop maar met fronten", song: "Happen Naar De Baas" },
  { word: "DRAAIT", lyric: "je draait je bil voor me", song: "Zilt" },
  { word: "SMOKEN", lyric: "want wij, smoken, alleen wiet", song: "Willie Wartaal Is Een Baas" },
  { word: "KOOKT", lyric: "Soms kookt ze voor me", song: "Tante Lien" },
  { word: "PRETTIG", lyric: "37 jaar, je vind het prettig maar", song: "Vijf Sterren Abbo" },
  { word: "MOKKEL", lyric: "laat het mokkel daar maar", song: "Hollereer" },
  { word: "CHILLEN", lyric: "We chillen chillen dope dope", song: "Buma In Me Zak" },
  { word: "FEEST", lyric: "heerlijk feestbeest", song: "Tante Lien" },
  { word: "GAPPIE", lyric: "kijk je gappie leeft zoet", song: "Sterrenstof" },
  { word: "JUNKIE", lyric: "komt er een junkie naar me toe voor een euro", song: "Watskeburt?!" },
  { word: "WEDEROM", lyric: "Vieze, wederom het vieste", song: "Aldiedingen" },
  { word: "VALSE", lyric: "voel die valse noten en daarna", song: "Pijpjes" },
  { word: "PATAT", lyric: "patat voor de kindertjes", song: "Pappa Is Thuis" },
  { word: "BIKKEL", lyric: "van deze baardenbikkel", song: "The Big Smurfout" },
  { word: "ORGEL", lyric: "Zie ik hem met een oorbel in op een orgel spelen", song: "Hoed Rits" },
  { word: "OUTFIT", lyric: "outfit als op je bornday", song: "Luek" },
  { word: "VISJES", lyric: "er zwemmen heel veel visjes in de zee", song: "Hengel At A Bitch" },
  { word: "FEESTJE", lyric: "Een crazy feestje in me hoofdje", song: "Stay Black" },
  { word: "ESQUIAR", lyric: "Yo quiero esquiar", song: "Get Spanish" },
  { word: "DAMSKO", lyric: "van damsko naar coevorden", song: "Centje Centje" },
  { word: "TRAVESTIET", lyric: "Flamboyant als een travestiet" },
  { word: "PLEZIER", lyric: "als je je vader effe een plezier", song: "Centje Centje" },
  { word: "WAGGIE", lyric: "voor waggie ze rijdt", song: "Tante Lien" },
  { word: "KRAMP", lyric: "Kramp in me maag, drank in d'r", song: "Hot Hot Hot" },
  { word: "ZONNEGOD", lyric: "Nee fok geen zonneman, ben een zonnegod", song: "Hot Hot Hot" },
  { word: "ZALEN", lyric: "Verkopen zalen uit in designer op stage", song: "Luek" },
  { word: "SAPPIE", lyric: "leeft zoet als een sappie", song: "Sterrenstof" },
  { word: "SMILE", lyric: "killer smile, jopen defy", song: "Tante Lien" },
  { word: "DONKER", lyric: "lekker in het donker", song: "Hou Het Straat" },
  { word: "BIETJE", lyric: "sneeuwpoppen met mn bopje bietjes", song: "Vette Kerst" },
  { word: "LIDL", lyric: "Van de Lidl naar de Ap'" },
  { word: "SCHWUNG", lyric: "De schwung is impeccable", song: "Aldiedingen" },
  { word: "PLASSEN", lyric: "je wast je handen al tijdens het plassen", song: "Watskeburt?!" },
  { word: "BLOEMEN", lyric: "Met jou, tussen de bloemen en bergen", song: "Wittewijnmuziek" },
  { word: "MOKERS", lyric: "M'n mokers komen aan als loden", song: "So Duits" },
  { word: "SMIECHT", lyric: "Ben een leugenaar een smiecht", song: "Happen Naar De Baas" },
  { word: "VISSEN", lyric: "alles van haar vissenspleet", song: "Elektrotechnique" },
  { word: "PILLEN", lyric: "tot zondagmiddag op de pillen", song: "Bertje Vs Yayo" },
  { word: "SKATTIE", lyric: "ai ai ik ben een skattie", song: "Opkepleurt" },
  { word: "TATTOOS", lyric: "Tattoos op je snoet en je handen", song: "Luek" },
  { word: "WHISKY", lyric: "Whisky, India, Whisky", song: "Tante Lien" },
  { word: "BORSTEN", lyric: "kinnen omhoog borsten vooruit", song: "Hollereer" },
  { word: "METRO", lyric: "van de metro naar de trein", song: "Centje Centje" },
  { word: "SNIKKEL", lyric: "berenchickies die aan mijn snikkel zitten", song: "Laat De Beer Los" },
  { word: "FLESSIE", lyric: "een flessie cola voor me", song: "Centje Centje" },
  { word: "DISNEY", lyric: "naar een walt disney film", song: "Hou Het Straat" },
  { word: "TIETEN", lyric: "En alles wat ik zie, is tieten zonder hoofden" },
  { word: "UITJES", lyric: "Zijn het uitjes of sjalotten", song: "De Musical" },
  { word: "ANDIJVIE", lyric: "je bent goed voor stampen als andijvie", song: "Pappa Is Thuis" },
  { word: "VONKEN", lyric: "Want die vonken springen over", song: "Voor Jou" },
  { word: "HANDTAS", lyric: "Handtas, lippenstift, hair", song: "Tante Lien" },
  { word: "GLAZEN", lyric: "geef die glazen, laat ze vullen", song: "Gemist" },
  { word: "GABBER", lyric: "Ik rel als een gabber die gesnoven heeft", song: "Drie Keer Niks" },
  { word: "HANDEN", lyric: "Handen in de lucht voor het refrein", song: "Luek" },
  { word: "ETTERBAK", lyric: "Hangt de etterbak uit makkelie", song: "Happen Naar De Baas" },
  { word: "RIMPELS", lyric: "bespaar je de rimpels", song: "Hollereer" },
  { word: "KENKERLAM", lyric: "Wartaal is kenkerlam" },
  { word: "ZWEMPAK", lyric: "Faka zwempak, dit is het plan", song: "Zilt" },
  { word: "BROEDER", lyric: "Maar broeder, vergeet dat", song: "Sterrenstof" },
  { word: "DOEKOE", lyric: "Van je doekoe, je flus", song: "Sorry" },
  { word: "ROZEN", lyric: "wou rozen voor je kopen", song: "Voor Jou" },
  { word: "WIJFFIE", lyric: "dus wijffie schud dat lijffie", song: "Pappa Is Thuis" },
  { word: "ZUIPEN", lyric: "Dus we zuipen, tot we kruipen", song: "Willie Wartaal Is Een Baas" },
  { word: "BUBBELS", lyric: "diep in de zee met al die bubbels", song: "Hou Het Straat" },
  { word: "TROTS", lyric: "Helemaal trots op die apenrots", song: "Luek" },
  { word: "SCHEUR", lyric: "Als ik over, over je heen scheur", song: "Vijf Sterren Abbo" },
  { word: "MEISJES", lyric: "en mooie meisjes gaan mee", song: "Flap Flap" },
  { word: "SCHURK", lyric: "Fieze fur, ik ben een schurk", song: "Voor Jou" },
  { word: "JALOEZIE", lyric: "alle smurfen worden groen van jaloezie", song: "The Big Smurfout" },
  { word: "SLAPPE", lyric: "dag slappe lul grote mond", song: "Laat De Beer Los" },
  { word: "SIMPEL", lyric: "hou het sickie zo simpel", song: "Hollereer" },
  { word: "BLAKA", lyric: "blaka staat buiten", song: "Huilend Naar De Club" },
  { word: "KANKER", lyric: "karl kanker kani's uurgh", song: "Hollereer" },
  { word: "TEFFEN", lyric: "en of je ff op wil teffen", song: "Centje Centje" },
  { word: "PARANOIA", lyric: "daarom ik ben een beetje paranoia", song: "Centje Centje" },
  { word: "GEZIN", lyric: "Want we zijn niet meer gezin", song: "Wittewijnmuziek" },
  { word: "GOUDEN", lyric: "Oogverblindend, m'n gouden haar", song: "De Musical" },
  { word: "TROMPET", lyric: "Rettekeket mijn trompet word hi", song: "Drie Keer Niks" },
  { word: "SMAKEN", lyric: "Je zal me vast heel erg lekker smaken", song: "Luek" },
  { word: "HEUVELS", lyric: "In de heuvels zonder het gepeupel", song: "Wittewijnmuziek" },
  { word: "VOETJES", lyric: "haalt die voetjes van de vloer", song: "Flap Flap" },
  { word: "OCHTEND", lyric: "Ik heb die ochtend fris", song: "Vijf Sterren Abbo" },
  { word: "LASTIG", lyric: "Ze was hele dag lastig, nu mis", song: "Wittewijnmuziek" },
  { word: "WATSKE", lyric: "niet van watske bekkie en of", song: "Bekkie" },
  { word: "CLITJE", lyric: "omdat ik aan een clitje zit", song: "Zilt" },
  { word: "WIEBEL", lyric: "wiebel je lafje tafje", song: "Er Is Een Hitje" },
  { word: "RIMMEN", lyric: "kom niet skeer aan de rimmen", song: "Hollereer" },
  { word: "DIKZAK", lyric: "Alle dikzakken willen op", song: "Sterrenstof" },
  { word: "HAUTE", lyric: "saus op me shirt bière op me haute", song: "Hollereer" },
  { word: "GARCON", lyric: "jonge garçon in commune des", song: "Flap Flap" },
  { word: "GLAASJE", lyric: "pappa z'n glaasje", song: "Pappa Is Thuis" },
  { word: "HEUPEN", lyric: "Je lippen, je mond, je heupen", song: "Voor Jou" },
  { word: "TALENT", lyric: "wat doet dat bekende talentje", song: "Centje Centje" },
  { word: "SLIPPER", lyric: "breng maar m'n slipper", song: "Pappa Is Thuis" },
  { word: "SCHAPEN", lyric: "Lekker warm met de rest van de schapen", song: "Luek" },
  { word: "GEROOKT", lyric: "Wie rookt er het stoerst wie heb", song: "Luek" },
  { word: "ERFENIS", lyric: "Van je erfenis kom maar op", song: "Sorry" },
  { word: "DREMPEL", lyric: "Oh, een drempel, verkeersdrempel", song: "Vijf Sterren Abbo" },
  { word: "HAMER", lyric: "je bent een hamer zonder klap", song: "Opkepleurt" },
  { word: "BEROEP", lyric: "het lijkt wel m'n beroep", song: "'t Gaat Te Fur" },
  { word: "DAKLOZE", lyric: "Ik ben een dakloze", song: "Ik Wil Me Lekkevoele" },
  { word: "SMAAKJE", lyric: "'k wil je leren kennen hoe is je smaakje", song: "Hengel At A Bitch" },
  { word: "SJEMBEK", lyric: "Je bent een sjembek dat zeurt", song: "Watskeburt?!" },
  { word: "WIEPEN", lyric: "Laat de buren maar genieten, want we wiepen op het tempo" },
  { word: "BLAZEN", lyric: "Maar ik ga door met blazen en spacen", song: "Willie Wartaal Is Een Baas" },
  { word: "LICHAAMSSAP", lyric: "Cocktails in de nacht gemaakt van lichaamssap" },
  { word: "BARKIE", lyric: "Trek een barkie uit de muur", song: "Een Barkie" },
  { word: "DECOR", lyric: "Westertoren als decor", song: "Een Barkie" },
  { word: "GEZEUR", lyric: "Is bij jouw alles rustig of gezeur met de buur", song: "Watskeburt?!" },
  { word: "CHEMIE", lyric: "We hadden alle soorten chemi-chemi-cali", song: "Gemist" },
  { word: "VACHT", lyric: "Koetjesrepen in me vacht", song: "Shenkie" },
  { word: "DOUCHEN", lyric: "ik hoef dus niet te douchen", song: "Bertje Vs Yayo" },
  { word: "FLAPPEN", lyric: "Die jongens willen flappen van jou", song: "Sorry" },
  { word: "KLEREN", lyric: "breng me kleren want ik blijf", song: "Pappa Is Thuis" },
  { word: "GROETEN", lyric: "groeten aan je tante", song: "Tante Lien" },
  { word: "WORMEN", lyric: "Vrat wormen en krekels", song: "Stay Black" },
  { word: "KLANK", lyric: "luister naar die klank", song: "Flap Flap" },
  { word: "CHORIZO", lyric: "voor die ho's chorizo", song: "Get Spanish" },
  { word: "WAPPIE", lyric: "mamma altijd wappie", song: "Sterrenstof" },
  { word: "TAFEL", lyric: "In hotel, ik gooi je op de tafel", song: "Wittewijnmuziek" },
  { word: "BREEZER", lyric: "b-b-breezer in je nekkie dus", song: "Bekkie" },
  { word: "KAKKER", lyric: "de dapen kakker en hartjes lakker", song: "Laat De Beer Los" },
  { word: "STINKEN", lyric: "Kijk me stinken, niet normaal", song: "De Musical" },
  { word: "RUDOLPH", lyric: "neus rood net als rudolph", song: "Vette Kerst" },
  { word: "SLORDIG", lyric: "Slordig en onhandelbaar, cake op m'n broek", song: "Buma In Me Zak" },
  { word: "KEUKEN", lyric: "er is woodgrain in de keuken", song: "Pappa Is Thuis" },
  { word: "HUILEN", lyric: "zit ik thuis uit te huilen", song: "Bertje Vs Yayo" },
  { word: "KARPETJE", lyric: "Ik wil spelen met je, op een geel karpetje", song: "Gemist" },
  { word: "SCHOOL", lyric: "Ik ging zelf naar school", song: "Sterrenstof" },
  { word: "PAPLEPEL", lyric: "me met de paplepel ingegoten", song: "Pappa Is Thuis" },
  { word: "STRAKKE", lyric: "ow je hebt strakke bil hoor", song: "Opkepleurt" },
  { word: "HOKJES", lyric: "Terug naar je hokje als kroketten van de FEBO", song: "Drie Keer Niks" },
  { word: "HENTAI", lyric: "Het is die hentai sempai", song: "Drie Keer Niks" },
  { word: "GAATJES", lyric: "vul je gaatjes met je zaadjes", song: "Laat De Beer Los" },
  { word: "SPANGE", lyric: "Spange japanse ho's zeggen Nanda yo", song: "Drie Keer Niks" },
  { word: "GRIETJES", lyric: "zijn die grietjes die Pepijn steeds pakt", song: "Pijpjes" },
  { word: "GASTJE", lyric: "ik als gastje doe me pasje", song: "Pappa Is Thuis" },
  { word: "TJONGE", lyric: "tjongejonge check die blonde", song: "Flap Flap" },
  { word: "BUSPAS", lyric: "buspas, pas verlopen dus ik pas", song: "'t Gaat Te Fur" },
  { word: "STEKKER", lyric: "stekker in je mond hou je bek", song: "Elektrotechnique" },
  { word: "POEPEN", lyric: "te dom om te poepen", song: "Hollereer" },
  { word: "GRIMY", lyric: "Grimy ass gat en geletterde pappie", song: "Happen Naar De Baas" },
  { word: "TJOERIES", lyric: "eentje voor je tjoeries", song: "Shenkie" },
  { word: "PINNEN", lyric: "Jij huilen dat je niet gaat pinnen", song: "Happen Naar De Baas" },
  { word: "DUIVEL", lyric: "Uit de spleet van de duivel", song: "Buma In Me Zak" },
  { word: "POLIZEI", lyric: "De Polizei keek opzij", song: "Tante Lien" },
  { word: "TIENTJE", lyric: "Ik gooi tien tientjes op de bar", song: "Een Barkie" },
  { word: "KRAAK", lyric: "Ik kraak wat af noem me Jaap", song: "Shenkie" },
  { word: "PASJES", lyric: "ik heb pasjes tot een uur", song: "Pappa Is Thuis" },
  { word: "SLAK", lyric: "En elke dag als een slak, onze lichaams drijfnat" },
  { word: "BIPS", lyric: "Op je bolle bips na" },
  { word: "BAKKA", lyric: "Ik wil die bakka slappen met een steelpan", song: "Ze Is Pas Net Begonnen" },
  { word: "DONDER", lyric: "ben een dondergod", song: "Elektrotechnique" },
  { word: "STRALEN", lyric: "Bergen op achtergrond, zonnestralen uit mond", song: "Wittewijnmuziek" },
  { word: "GEWOON", lyric: "Je mag gewoon in de bus", song: "Vijf Sterren Abbo" },
  { word: "BRUTAAL", lyric: "vaak liet ik je gaan al was je brutaal", song: "Laat De Beer Los" },
  { word: "BEDDJE", lyric: "ik zet het campingbedje op", song: "Wittewijnmuziek" },
  { word: "SLETTEN", lyric: "de sletten ik breng", song: "Sterrenstof" },
  { word: "WORST", lyric: "Spaanse worst sowieso", song: "Get Spanish" },
  { word: "MACCIE", lyric: "je kan me vinden in de maccie", song: "Hollereer" },
  { word: "SCHEEL", lyric: "ben immer clean tot je scheel", song: "Bekkie" },
  { word: "SPANGIE", lyric: "Weet je nog die ene week in Spangie", song: "Gemist" },
  { word: "BERGEN", lyric: "Tussen de zonnebloemen en konijnenkeutels", song: "Wittewijnmuziek" },
  { word: "TEPEL", lyric: "mag ik je tepel likken", song: "Opkepleurt" },
  { word: "POKOE", lyric: "ze draaien je pokoe dit is wittewijnmuziek", song: "Wittewijnmuziek" },
  { word: "WAKKER", lyric: "Net wakker, je weet wat ik bedoel gast", song: "'t Gaat Te Fur" },
  { word: "MELKWEG", lyric: "ga je straks mee naar de Melkweg", song: "'t Gaat Te Fur" },
  { word: "FLIKKER", lyric: "Geile beer, geile flikker, ouwe pik", song: "Gemist" },
  { word: "SLETJES", lyric: "sletjes zijn welkom", song: "Flap Flap" },
  { word: "OUDER", lyric: "Ietsje ouder, maar nog steeds amazing", song: "Tante Lien" },
  { word: "OESTERS", lyric: "Lauwe oesters daar beneden", song: "Hot Hot Hot" },
  { word: "RAKET", lyric: "gaan vanavond per raket naar de sterren", song: "Gemist" },
  { word: "WEERTJE", lyric: "Stap naar buiten en zie dat het weertje weer", song: "'t Gaat Te Fur" },
  { word: "VOCAAL", lyric: "Komen die vocalen nog of moet ik beginnen", song: "Watskeburt?!" },
  { word: "BLOOTJE", lyric: "Die ene keer met ze tweeën in ons blootje" },
  { word: "MOEDER", lyric: "De een is je moeder en de ander is je zus", song: "Zilt" },
  { word: "LIEDJE", lyric: "dat liedje van jouw", song: "Hoed Rits" },
  { word: "BLONDE", lyric: "tjongejonge check die blonde", song: "Flap Flap" },
  { word: "POLONAISE", lyric: "zonder polonaise of in de tuin", song: "Pijpjes" },
  { word: "KOUWE", lyric: "Kouwe klats achterin als hee wie is er", song: "'t Gaat Te Fur" },
  { word: "SMAKKEN", lyric: "hoor de boys smakken", song: "Hengel At A Bitch" },
  { word: "HEFTIG", lyric: "Dit is BPM 69, lekker heftig" },
  { word: "POKJE", lyric: "pak je pokje bel je mensen", song: "Er Is Een Hitje" },
  { word: "BIERJE", lyric: "en we komen met bierje", song: "Flap Flap" },
  { word: "SNOESJE", lyric: "me snoesje bleek een hoer", song: "Flap Flap" },
  { word: "LOOPSE", lyric: "voel je het als een loopse teef", song: "Laat De Beer Los" },
  { word: "WIJVEN", lyric: "Drank, gelach en domme wijven" },
  { word: "TANTE", lyric: "'n sexy jonge Tante Lien" },
  { word: "DRONKEN", lyric: "De dronken P is je heer", song: "Happen Naar De Baas" },
  { word: "MIETJE", lyric: "ik ben geen mietje ik maak geen liedje", song: "Laat De Beer Los" },
  { word: "MOSSEL", lyric: "Mademoiselle met je natte mossel", song: "Hot Hot Hot" },
  { word: "KROEG", lyric: "ik ga wel naar de kroeg", song: "Opkepleurt" },
  { word: "BENEN", lyric: "Ze breekt je benen", song: "Tante Lien" },
  { word: "DAPPER", lyric: "dapper dat is anders", song: "Flap Flap" },
  { word: "DROGE", lyric: "ik heb een ontzettend droge mond", song: "Centje Centje" },
  { word: "BIKINI", lyric: "Die en die bikini: interessant", song: "Zilt" },
  { word: "BIERTJE", lyric: "Ik drink een bok bok, biertje hier, bok biertje daar, bok biertje hier" },
  { word: "STANK", lyric: "eentje voor je stank", song: "Shenkie" },
];
